# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'lelylan-ios' do
pod 'AFNetworking', '~> 2.0'
pod "OAuth.io"
end

target 'lelylan-iosTests' do

end

